import type { Metadata } from "next";
import { Roboto, Playfair_Display } from "next/font/google";
import "./globals.css";
import { AdviceProvider } from "./context/AdviceContext";

const roboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap'
});

const playFair = Playfair_Display ({
  variable: "--font-playfair-display",
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${playFair.variable}`}>
        <AdviceProvider>
        {children}
        </AdviceProvider>
      </body>
    </html>
  );
}
